### ISSUE TITLE
Training Time 

### ISSUE THREAD

**Issue by vk841997** [SaulZhang/Video_Prediction_ZOO#1]
Hi ,
   I have run this code and it takes around 10 days to run the code.
Can you just let me know the running time taken by you and on which gpu ?

Thanks in advance.

**Comment by pushthebell** [comment]
Hi. Do you think you can tell me how many epochs have you run?

**Comment by vk841997** [comment]
For 100 epochs it takes around 5 days on sinlge gpu Nvidia GTX 1080 ti

**Comment by pushthebell** [comment]
Were the parameter values like below for your training?

Batch size : 20
Image size : 256*256
The # of training data images : about 41K (entire KITTI dataset)
n_cpu : 0

**Comment by vk841997** [comment]
batch size = 5 
n_cpu =0 
image size = 256 * 256
no of training data images : 39 K , 2 K for validation

**Comment by pushthebell** [comment]
Okay, Thank You!:)
